export type Lang = "el" | "en";
export const languages: Lang[] = ["el", "en"];
export const copy = {
  en: {
    nav: ["Home", "Services", "About", "Contact"],
    quote: "Request a quote",
    login: "Client portal",
    eyebrow: "LEGAL CLARITY. HUMAN CONNECTION.",
    hero: "A clearer path",
    heroAccent: "forward.",
    intro:
      "Legal matters can feel complex. Your next step shouldn’t. Expert guidance, personal attention, and a secure digital experience — all in one place.",
    explore: "Explore our services",
    trust: ["Personal approach", "Clear communication", "Digital convenience"],
    servicesTag: "EXPERTISE THAT MATTERS",
    servicesTitle: "Life happens. We help you navigate it.",
    servicesIntro:
      "From a fresh financial start to a new chapter abroad, find the support that fits your situation.",
    all: "View all services",
    learn: "Discover service",
    processTag: "A SIMPLE WAY FORWARD",
    processTitle: "From first question to clear direction.",
    steps: [
      "Tell us what you need",
      "Receive a tailored proposal",
      "Move forward together",
    ],
    stepText: [
      "Choose a service and share a brief overview of your matter.",
      "We review your request and outline the scope and next steps.",
      "Follow your case, documents and updates in your client portal.",
    ],
    ctaTitle: "Your next chapter starts with a conversation.",
    ctaText: "Let’s understand your situation and find the right way forward.",
    footer: "Thoughtful legal guidance. Wherever life takes you.",
    rights: "All rights reserved.",
    demo: "Phase 1 demonstration · Fictional data · No information is saved.",
    aboutTitle: "Expertise with a human perspective.",
    aboutText:
      "ENDIKON brings clarity and care to legal matters. Our vision is a more approachable legal experience: thoughtful guidance, transparent communication and tools that keep you informed.",
    aboutValues: [
      "Clarity at every step",
      "Care for your circumstances",
      "A modern legal experience",
    ],
    contactTitle: "Let’s start a conversation.",
    contactText:
      "Have a question about the process? Explore our services or send a demonstration enquiry below.",
    name: "Full name",
    email: "Email address",
    phone: "Phone (optional)",
    details: "Brief description",
    service: "Service",
    submit: "Preview request",
    success:
      "Demo request previewed. Nothing was sent or stored. Please do not enter real personal information.",
    notice:
      "Demo form: use fictional details only. Submissions are not sent or stored.",
    quoteTitle: "The right guidance starts here.",
    quoteText:
      "Tell us a little about your matter. A tailored proposal comes after an individual review — no public or automatic pricing.",
    scope: "HOW WE CAN HELP",
    requestTitle: "Tell us about your situation",
    loginTitle: "Your legal journey, in one place.",
    loginText:
      "Explore the client experience with fictional cases. Authentication is not connected in this prototype.",
    registerTitle: "A more connected legal experience.",
    registerText:
      "Account creation will be available with secure backend integration. For now, explore the demonstration.",
    enter: "Explore client demo",
    admin: "Explore admin demo",
    dashboard: "Overview",
    cases: "Cases",
    documents: "Documents",
    messages: "Messages",
    notifications: "Notifications",
    welcome: "Good morning, Alex.",
    dashboardIntro: "A little more clarity. A step closer to resolution.",
    active: "Active cases",
    pending: "Documents needed",
    quoteStatus: "Quote status",
    review: "Under review",
    caseName: "Residence permit renewal",
    caseSub: "Case EN-2026-014 · Fictional example",
    timeline: [
      "Request received",
      "Initial review",
      "Documents requested",
      "Application preparation",
    ],
    required: "Required documents",
    docNames: ["Identity document", "Proof of residence", "Application form"],
    received: "Received",
    needed: "Awaiting document",
    upload: "Preview upload",
    uploadNote:
      "Uploads are disabled in this demo. No files are selected or transmitted.",
    message:
      "Your document checklist is ready. You can review the next steps below.",
    advisor: "Demo legal advisor",
    quoteLabel: "Your tailored proposal",
    quoteDesc: "Scope review in progress. No quote has been issued.",
    adminTitle: "A thoughtful view of every case.",
    adminIntro:
      "Manage your demonstration workspace. All records below are fictional.",
    requests: "Incoming requests",
    clients: "Mock clients",
    prepare: "Prepare quote",
    requestDoc: "Request document",
    action: "Demo action previewed. No changes were saved or sent.",
    back: "Back to services",
    specific: "Matter type",
    consent:
      "I understand this is a demonstration and will use fictional information only.",
    register: "Register",
    secure: "Designed for clarity",
    home: "Home",
    notFound: "Page not found",
    more: "View case details",
  },
  el: {
    nav: ["Αρχική", "Υπηρεσίες", "Σχετικά", "Επικοινωνία"],
    quote: "Ζητήστε προσφορά",
    login: "Πύλη πελάτη",
    eyebrow: "ΝΟΜΙΚΗ ΣΑΦΗΝΕΙΑ. ΑΝΘΡΩΠΙΝΗ ΣΧΕΣΗ.",
    hero: "Το επόμενο βήμα,",
    heroAccent: "με σιγουριά.",
    intro:
      "Τα νομικά ζητήματα μπορεί να είναι σύνθετα. Το επόμενο βήμα σας δεν χρειάζεται να είναι. Εξειδικευμένη καθοδήγηση, προσωπική φροντίδα και μια σύγχρονη ψηφιακή εμπειρία.",
    explore: "Δείτε τις υπηρεσίες",
    trust: ["Προσωπική προσέγγιση", "Ξεκάθαρη επικοινωνία", "Ψηφιακή ευκολία"],
    servicesTag: "ΕΞΕΙΔΙΚΕΥΣΗ ΜΕ ΟΥΣΙΑ",
    servicesTitle: "Η ζωή προχωρά. Είμαστε δίπλα σας.",
    servicesIntro:
      "Από μια νέα οικονομική αρχή έως ένα νέο κεφάλαιο στο εξωτερικό, βρείτε την υποστήριξη που ταιριάζει στην περίπτωσή σας.",
    all: "Όλες οι υπηρεσίες",
    learn: "Δείτε την υπηρεσία",
    processTag: "ΜΙΑ ΑΠΛΗ ΔΙΑΔΡΟΜΗ",
    processTitle: "Από την πρώτη ερώτηση, στην ξεκάθαρη κατεύθυνση.",
    steps: [
      "Πείτε μας τι χρειάζεστε",
      "Λάβετε μια εξατομικευμένη πρόταση",
      "Προχωράμε μαζί",
    ],
    stepText: [
      "Επιλέξτε υπηρεσία και περιγράψτε σύντομα το ζήτημά σας.",
      "Εξετάζουμε το αίτημά σας και προσδιορίζουμε το πλαίσιο και τα επόμενα βήματα.",
      "Παρακολουθήστε την υπόθεση, τα έγγραφα και τις ενημερώσεις στην πύλη πελάτη.",
    ],
    ctaTitle: "Το επόμενο κεφάλαιο ξεκινά με μια συζήτηση.",
    ctaText:
      "Ας κατανοήσουμε την περίπτωσή σας και ας βρούμε τον κατάλληλο δρόμο.",
    footer: "Νομική καθοδήγηση με φροντίδα. Όπου σας οδηγεί η ζωή.",
    rights: "Με επιφύλαξη παντός δικαιώματος.",
    demo: "Επίδειξη Φάσης 1 · Πλασματικά δεδομένα · Δεν αποθηκεύονται πληροφορίες.",
    aboutTitle: "Εξειδίκευση με ανθρώπινη ματιά.",
    aboutText:
      "Η ENDIKON φέρνει σαφήνεια και φροντίδα στα νομικά ζητήματα. Όραμά μας είναι μια πιο προσιτή νομική εμπειρία: ουσιαστική καθοδήγηση, διαφανής επικοινωνία και εργαλεία που σας κρατούν ενήμερους.",
    aboutValues: [
      "Σαφήνεια σε κάθε βήμα",
      "Φροντίδα για την περίπτωσή σας",
      "Μια σύγχρονη νομική εμπειρία",
    ],
    contactTitle: "Ας ξεκινήσουμε μια συζήτηση.",
    contactText:
      "Έχετε μια ερώτηση για τη διαδικασία; Εξερευνήστε τις υπηρεσίες μας ή δοκιμάστε τη φόρμα επίδειξης παρακάτω.",
    name: "Ονοματεπώνυμο",
    email: "Διεύθυνση email",
    phone: "Τηλέφωνο (προαιρετικό)",
    details: "Σύντομη περιγραφή",
    service: "Υπηρεσία",
    submit: "Προεπισκόπηση αιτήματος",
    success:
      "Έγινε προεπισκόπηση του δοκιμαστικού αιτήματος. Δεν στάλθηκε ή αποθηκεύτηκε τίποτα. Μην εισάγετε πραγματικά προσωπικά στοιχεία.",
    notice:
      "Δοκιμαστική φόρμα: χρησιμοποιήστε μόνο πλασματικά στοιχεία. Τα αιτήματα δεν στέλνονται ή αποθηκεύονται.",
    quoteTitle: "Η σωστή καθοδήγηση ξεκινά εδώ.",
    quoteText:
      "Πείτε μας λίγα λόγια για το ζήτημά σας. Η εξατομικευμένη πρόταση ακολουθεί την αξιολόγηση — χωρίς δημόσιες ή αυτόματες τιμές.",
    scope: "ΠΩΣ ΜΠΟΡΟΥΜΕ ΝΑ ΒΟΗΘΗΣΟΥΜΕ",
    requestTitle: "Πείτε μας για την περίπτωσή σας",
    loginTitle: "Η νομική σας διαδρομή, σε ένα σημείο.",
    loginText:
      "Εξερευνήστε την εμπειρία πελάτη με πλασματικές υποθέσεις. Η σύνδεση δεν είναι ενεργή σε αυτή την έκδοση.",
    registerTitle: "Μια πιο συνδεδεμένη νομική εμπειρία.",
    registerText:
      "Η δημιουργία λογαριασμού θα ενεργοποιηθεί με ασφαλή σύνδεση backend. Προς το παρόν, εξερευνήστε την επίδειξη.",
    enter: "Είσοδος στο demo πελάτη",
    admin: "Είσοδος στο demo διαχειριστή",
    dashboard: "Επισκόπηση",
    cases: "Υποθέσεις",
    documents: "Έγγραφα",
    messages: "Μηνύματα",
    notifications: "Ειδοποιήσεις",
    welcome: "Καλημέρα, Αλέξη.",
    dashboardIntro: "Λίγη περισσότερη σαφήνεια. Ένα βήμα πιο κοντά στη λύση.",
    active: "Ενεργές υποθέσεις",
    pending: "Έγγραφα σε αναμονή",
    quoteStatus: "Κατάσταση προσφοράς",
    review: "Υπό αξιολόγηση",
    caseName: "Ανανέωση άδειας διαμονής",
    caseSub: "Υπόθεση EN-2026-014 · Πλασματικό παράδειγμα",
    timeline: [
      "Παραλαβή αιτήματος",
      "Αρχική αξιολόγηση",
      "Αίτημα εγγράφων",
      "Προετοιμασία αίτησης",
    ],
    required: "Απαραίτητα έγγραφα",
    docNames: [
      "Έγγραφο ταυτοποίησης",
      "Αποδεικτικό κατοικίας",
      "Έντυπο αίτησης",
    ],
    received: "Παραλήφθηκε",
    needed: "Αναμονή εγγράφου",
    upload: "Προεπισκόπηση μεταφόρτωσης",
    uploadNote:
      "Οι μεταφορτώσεις είναι απενεργοποιημένες στο demo. Δεν επιλέγονται ή μεταδίδονται αρχεία.",
    message:
      "Η λίστα των εγγράφων σας είναι έτοιμη. Δείτε τα επόμενα βήματα παρακάτω.",
    advisor: "Νομικός σύμβουλος επίδειξης",
    quoteLabel: "Η εξατομικευμένη πρότασή σας",
    quoteDesc: "Αξιολόγηση πλαισίου σε εξέλιξη. Δεν έχει εκδοθεί προσφορά.",
    adminTitle: "Ουσιαστική εικόνα για κάθε υπόθεση.",
    adminIntro:
      "Διαχειριστείτε τον δοκιμαστικό χώρο εργασίας. Όλες οι εγγραφές είναι πλασματικές.",
    requests: "Εισερχόμενα αιτήματα",
    clients: "Δοκιμαστικοί πελάτες",
    prepare: "Σύνταξη προσφοράς",
    requestDoc: "Αίτημα εγγράφου",
    action:
      "Προεπισκόπηση δοκιμαστικής ενέργειας. Δεν αποθηκεύτηκαν ή στάλθηκαν αλλαγές.",
    back: "Πίσω στις υπηρεσίες",
    specific: "Είδος ζητήματος",
    consent:
      "Κατανοώ ότι πρόκειται για επίδειξη και θα χρησιμοποιήσω μόνο πλασματικά στοιχεία.",
    register: "Εγγραφή",
    secure: "Σχεδιασμένο για σαφήνεια",
    home: "Αρχική",
    notFound: "Η σελίδα δεν βρέθηκε",
    more: "Δείτε την υπόθεση",
  },
};
export const services = [
  {
    slug: "debt-settlement",
    icon: "financial",
    en: {
      title: "Debt settlement",
      subtitle: "A fresh financial start.",
      desc: "Navigate debt arrangements and the extrajudicial mechanism with a clear understanding of your options.",
      topics: [
        "Extrajudicial mechanism",
        "Creditor arrangements",
        "Debt assessment",
      ],
      options: [
        "Extrajudicial application",
        "Debt arrangement",
        "Initial assessment",
      ],
    },
    el: {
      title: "Ρύθμιση οφειλών",
      subtitle: "Μια νέα οικονομική αρχή.",
      desc: "Καθοδήγηση στη ρύθμιση οφειλών και στον εξωδικαστικό μηχανισμό, με ξεκάθαρη εικόνα των επιλογών σας.",
      topics: [
        "Εξωδικαστικός μηχανισμός",
        "Ρυθμίσεις με πιστωτές",
        "Αξιολόγηση οφειλών",
      ],
      options: ["Αίτηση εξωδικαστικού", "Ρύθμιση οφειλών", "Αρχική αξιολόγηση"],
    },
  },
  {
    slug: "immigration",
    icon: "globe",
    en: {
      title: "Immigration & residence",
      subtitle: "Your next chapter, here.",
      desc: "Thoughtful support for residence permits, renewals and the legal steps of building a life in Greece.",
      topics: ["Residence permits", "Permit renewals", "Application guidance"],
      options: [
        "First residence permit",
        "Permit renewal",
        "Other immigration matter",
      ],
    },
    el: {
      title: "Μετανάστευση & διαμονή",
      subtitle: "Το επόμενο κεφάλαιο, εδώ.",
      desc: "Υποστήριξη για άδειες διαμονής, ανανεώσεις και τα νομικά βήματα μιας νέας ζωής στην Ελλάδα.",
      topics: ["Άδειες διαμονής", "Ανανέωση αδειών", "Καθοδήγηση αιτήσεων"],
      options: [
        "Πρώτη άδεια διαμονής",
        "Ανανέωση άδειας",
        "Άλλο μεταναστευτικό ζήτημα",
      ],
    },
  },
  {
    slug: "real-estate",
    icon: "home",
    en: {
      title: "Real estate & property",
      subtitle: "Solid ground for your decisions.",
      desc: "Make informed property decisions with support for transactions, ownership and legal due diligence.",
      topics: ["Property transactions", "Title review", "Ownership matters"],
      options: ["Purchase or sale", "Title review", "Property dispute"],
    },
    el: {
      title: "Ακίνητα & περιουσία",
      subtitle: "Σταθερή βάση για τις αποφάσεις σας.",
      desc: "Ενημερωμένες αποφάσεις για την περιουσία σας, με υποστήριξη στις συναλλαγές και στον νομικό έλεγχο.",
      topics: ["Συναλλαγές ακινήτων", "Έλεγχος τίτλων", "Ζητήματα ιδιοκτησίας"],
      options: ["Αγορά ή πώληση", "Έλεγχος τίτλων", "Περιουσιακή διαφορά"],
    },
  },
  {
    slug: "inheritance",
    icon: "inheritance",
    en: {
      title: "Inheritance",
      subtitle: "Protecting what matters.",
      desc: "Sensitive, practical guidance through succession, wills and inheritance-related obligations.",
      topics: [
        "Acceptance of inheritance",
        "Wills and succession",
        "Inheritance obligations",
      ],
      options: [
        "Acceptance of inheritance",
        "Will or succession",
        "Renunciation",
      ],
    },
    el: {
      title: "Κληρονομικά",
      subtitle: "Προστατεύοντας όσα έχουν αξία.",
      desc: "Πρακτική καθοδήγηση με ευαισθησία σε θέματα διαδοχής, διαθηκών και κληρονομικών υποχρεώσεων.",
      topics: [
        "Αποδοχή κληρονομιάς",
        "Διαθήκες και διαδοχή",
        "Κληρονομικές υποχρεώσεις",
      ],
      options: ["Αποδοχή κληρονομιάς", "Διαθήκη ή διαδοχή", "Αποποίηση"],
    },
  },
  {
    slug: "family-law",
    icon: "family",
    en: {
      title: "Family law",
      subtitle: "Care through life’s transitions.",
      desc: "A considered approach to family matters, with respect for your needs and the people involved.",
      topics: [
        "Separation and divorce",
        "Parenting arrangements",
        "Family agreements",
      ],
      options: [
        "Separation or divorce",
        "Parenting arrangements",
        "Family agreement",
      ],
    },
    el: {
      title: "Οικογενειακό δίκαιο",
      subtitle: "Φροντίδα στις αλλαγές της ζωής.",
      desc: "Προσεκτική προσέγγιση στα οικογενειακά ζητήματα, με σεβασμό στις ανάγκες σας και στους ανθρώπους που αφορούν.",
      topics: [
        "Διάσταση και διαζύγιο",
        "Ρυθμίσεις για τα παιδιά",
        "Οικογενειακές συμφωνίες",
      ],
      options: [
        "Διάσταση ή διαζύγιο",
        "Ρυθμίσεις για τα παιδιά",
        "Οικογενειακή συμφωνία",
      ],
    },
  },
  {
    slug: "other",
    icon: "other",
    en: {
      title: "Other legal matters",
      subtitle: "A starting point for your questions.",
      desc: "Every situation is different. Share your legal concern and explore an appropriate next step.",
      topics: ["Individual assessment", "Legal guidance", "Next-step planning"],
      options: ["Legal consultation", "Document review", "Other matter"],
    },
    el: {
      title: "Άλλα νομικά ζητήματα",
      subtitle: "Μια αφετηρία για τις ερωτήσεις σας.",
      desc: "Κάθε περίπτωση είναι διαφορετική. Μοιραστείτε το νομικό σας ζήτημα και εξερευνήστε το κατάλληλο επόμενο βήμα.",
      topics: [
        "Εξατομικευμένη αξιολόγηση",
        "Νομική καθοδήγηση",
        "Σχεδιασμός επόμενων βημάτων",
      ],
      options: ["Νομική συμβουλή", "Έλεγχος εγγράφου", "Άλλο ζήτημα"],
    },
  },
];
